### ISSUE TITLE
Warning: nerdpack:clone is not a nr1 command.

### ISSUE THREAD

**Issue by leslie-alldridge** [newrelic/nr1-observability-maps#17]
Hi team

My CLI says `Warning: nerdpack:clone is not a nr1 command.` and nr1 --version shows `@datanerd/nr1/0.3.0-beta.3.b20d65e win32-x64 node-v10.16.3`

Just wondering how I could proceed from here, thanks.

**Comment by Kav91** [comment]
Hi @leslie-alldridge that issue is not specific to this nerdpack.

Although it looks like you are on an old beta version. Could you please download the latest version and try again.
Alternatively since this nerdpack is also available in the app catalog you could install it from there too.

```
➜ nr1 nerdpack:clone
✖  Error: Missing required flag:
-r, --repo REPO  Repository location (either an HTTPS or SSH path)
See more help with --help

~ via ⬢ v10.16.2
➜ nr1 --version
@datanerd/nr1/1.22.2 darwin-x64 node-v10.16.3
```

**Comment by leslie-alldridge** [comment]
Thanks Kav I'll give it a shot!
