### ISSUE TITLE
Renaming of nodes crashes my map permanently

### ISSUE THREAD

**Issue by tashagooch** [newrelic/nr1-observability-maps#23]
We recently had the observability nerd pack pushed to our production account in New Relic by our account managers. I started working on an observability map for our network, which is made of of insights data being pulled in via api from PRTG. The data is no problem.  But I am running into bugs as I create the map.  

1st attempt:
I had 4 or 5 nodes / links created with hover data, I realized that I had mixed up 2 nodes. I attempted to rename the first node, meaning that briefly there would be 2 nodes with the same name. It didn't stop me from doing this, however it immediately went to a blank page in Chrome with "Ooops something went wrong" . There are no options to undo my change, it saves immediately upon change and so I have lost access to the map. 

2nd attempt:
I wasn't too far in, so I started a 2nd map, and got a bit further into it this time, but once again, when renaming a node (I did not give it a name that was in use) It immediately changed to "Oops something went wrong" and every time I try to load the map it goes to this screen, without any options to alter it. I attempted again today when getting in, and still cannot access.

I am on a Mac using OS 10 Mojave, I've tried it in both Chrome and Safari. I was working in Safari when it happened. 
I have VPN / Zscaler enabled on my work PC although I don't forsee that being an issue since it was working ok up to that point. 

I've let my act reps know who requested I open a ticket here. I'm including a screenshot as well as my developer code from loading the page in Chrome. 

Sidenote: I had set my default map to this, and had a dickens of a time trying to load the page repeatedly and get into the settings to change it back to default quickly before the Oops loaded and no settings were accessible. Prev to that I was unable to use the tool at all, as it immediately went to the failed dashboard without any of the settings at the top being displayed.

All that said, I am VERY excited about this tool once I can trust putting more effort into it, thank you so much for creating it!

[one.newrelic.com-Version 1- 1590523692647.log](https://github.com/newrelic/nr1-observability-maps/files/4684802/one.newrelic.com-Version.1-.1590523692647.log)

[one.newrelic.com-Version2 - 1590523649685.log](https://github.com/newrelic/nr1-observability-maps/files/4684803/one.newrelic.com-Version2.-.1590523649685.log)

![image](https://user-images.githubusercontent.com/65961037/82946068-ba0db900-9f6b-11ea-9cb8-70cccfbe1d1c.png)

**Comment by Kav91** [comment]
Hi @tashagooch thanks for the details, 2 quick questions.
1. Are there any errors in the console?
2. What version of the nerdpack are you on? 

Will try to replicate this in the mean time with the details you've provided.

**Comment by Kav91** [comment]
@tashagooch I've created a fix for this and improved the resiliency of checking the node and link data.

It is committed to master in this repo. However if you have deployed from the App Catalog, you will need to wait till this PR is merged so it is automatically updated for all users -> https://github.com/newrelic/nr1-catalog/pull/63 .

Hopefully early in the coming week.

**Comment by tashagooch** [comment]
Wow thank you so much for such a quick response and solution!  
I believe my new relic account guys deployed it from the catalogue but I'll check.
I checked and both my existing maps still give me the error, however could be that it didn't merge yet or that it wont help with past maps already in error state. I don't suppose there is anywhere in the console I'd be able to get at the data for the export of the broken maps. I'm briefly able to see the export code when I click the button but cant copy paste fast enough before it goes to oops error. 

In regards to your question about console errors I suspect you already found the log files with the error messages incl, but if you need something further just let me know. Sounds like you already have it under control tho. Appreciated!

**Comment by Kav91** [comment]
@tashagooch thanks for your patience so far.
I'm not sure if I've been able to replicate your situation, unless it is potentially fixed now.

So what I've done is improve the error handling so it should render your map config and additional error details instead of crashing out. So you'll be able to share those exact details if it occurs this time.

That capability is available in 0.6.6, if you've installed via the catalog once this PR -> https://github.com/newrelic/nr1-catalog/pull/66 is merged you'll be automatically updated.

If you are in a rush you can always deploy via the CLI manually.

**Comment by Kav91** [comment]
Should be resolved, closing now due to inactivity.
