### ISSUE TITLE
Unable to install latest version

### ISSUE THREAD

**Issue by hprins** [newrelic/nr1-observability-maps#25]
I tried installing this on Windows, but I am getting this error:

Installing dependencies…
Re-generating UUID…
x Error: Error on command: nr1 nerdpack:uuid --generate --force
--=-================

When I try with verbose option, this is what I get:

Installing dependencies…
added 394 packages in 14.123s
Re-generating UUID…
Sending usage event cliError
x Error: Error on command: nr1 nerdpack:uuid --generate --force

{ Error: spawnSync nr1 ENOENT
at Object.spawnSync (internal/child_process.js:1002:20)
at spawnSync (child_process.js:614:24)
at NerdpackCloneCommand._runChildProcessSync

-=-====================
I updated the cli and tried from another windows laptop, but I still get the same error.  I was able to make this work by cloning an older commit (c32b957).  I had similar issues with other Nerdpacks as well, e.g. Neon and Apdex Optimizer.  I was able to  make those work with older commits as well.

**Comment by Kav91** [comment]
@hprins this is not an observability maps issue, and not the correct place to raise.

I'm suspecting it's because you have not updated your nr1 cli before attempting to deploy.
Also you can install this nerdpack from the New Relic App Catalog without needing to use the CLI as well.

**Comment by hprins** [comment]
@Kav91 I did update the cli and received those errors.  I will unsubscribe and try vi the NR catalog just to see what happens.

**Comment by Kav91** [comment]
@hprins I don't have a windows machine to attempt to replicate. But this sounds like an issue with the CLI. Can you share the version you are running please?

I would attempt to completely delete the CLI, then reinstall. If still no success, we can raise it with the team responsible for the CLI.

**Comment by hprins** [comment]
@Kav91 here is the info:

CLI = @datanerd/nr1/1.22.2 win32-x64 node-v10.16.3
Git = git version 2.21.0.windows.1
NPM = 6.14.5
Thanks

**Comment by hprins** [comment]
@Kav91 I forgot to mention that I will delete CLI and try again, but will do later today... thanks again

**Comment by hprins** [comment]
@Kav91  same results from a new AWS instance.  Let me know if I need to move this to a different place.  Thanks

**Comment by markweitzel** [comment]
@hprins -- which branch did you clone that you got this working?

**Comment by hprins** [comment]
@markweitzel here is the info - https://github.com/newrelic/nr1-observability-maps/commit/c32b9575ff17923eb9163066e7d75e588ada4af4  thanks
