### ISSUE TITLE
Deployments showing empty list when app entities have recorded deployments 

### ISSUE THREAD

**Issue by ricegi** [newrelic/nr1-observability-maps#30]
## Description

In a few cases we've seen an empty deployment list within the map. The apps are confirmed as having deployments (see image).
![o-m-deployment-issue](https://user-images.githubusercontent.com/4061375/88422595-84911a80-cdb8-11ea-8870-a9031dac3200.png)

## Steps to Reproduce

Map with apps in which deployments have been recorded. 

## Additional context

We haven't validated this thoroughly - need to understand if the time picker will influence the deployment observed - that might be the usability root cause.

**Comment by Kav91** [comment]
As the map aims to provide a real time view, it just uses the default time window supplied by nerdgraph which is the last day.

**Comment by ricegi** [comment]
Awesome - thanks Kav - I'll conform the window with the reporter and update as needed. Thx for looking at this so quickly!

**Comment by ricegi** [comment]
A little bit more feedback. The context of the is seen to be a little misleading, since the alerts list seems to be a lot > than an  hour the expectation was set that the deployments would show within a similar bounded range. 

Maybe there is something we could do in the interm like indicating "no deployments in the past hour" on that tab - or some other visual indication.

**Comment by Kav91** [comment]
A message has been added so users can better understand.
