### ISSUE TITLE
Permssion control of observability maps dashboards

### ISSUE THREAD

**Issue by sekrish1** [newrelic/nr1-observability-maps#48]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary
Currently, anyone in the same account can modify an observability map. This may not be desirable, especially in large accounts

## Desired Behaviour
Add access control to the observability maps app so that only the creator and (say) admins can change a map.

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Possible Solution
Add an 'export as dashboard' feature to export the map as a dashboard and have it governed by the typical access rules for all dashboards
[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by Kav91** [comment]
Hey @sekrish1 unfortunately this is something that I cannot control or modify myself because of how NerdStorage permissions work for nerdpacks. I'm going to close this issue, but I will share it internally as I also think it would be great to have this functionality available.
