### ISSUE TITLE
chore: update package-lock.json

### ISSUE THREAD

**Issue by jbeveland27** [newrelic/nr1-observability-maps#5]
The version in the package-lock.json should match up to what's in the package.json (currently `0.4.7`). 

Should just need to run `npm install`.

package-lock.json:
```
"version": "0.4.6",
```

package.json:
```
"version": "0.4.7",
```
Might need to modify semantic-release-bot so it updates package-lock.json appropriately.

**Comment by Kav91** [comment]
Fixed thx.
