### ISSUE TITLE
Add Node - Need an option to select multiple entities 

### ISSUE THREAD

**Issue by sri-shetty** [newrelic/nr1-observability-maps#52]
![image](https://user-images.githubusercontent.com/52978309/102269036-13c6d800-3eea-11eb-8c49-9a5e392be0be.png)

**Comment by aries-zhang** [comment]
+1

This makes whoever's life miserable when they have to add many nodes on one map.

**Comment by Kav91** [comment]
Resolved in -> https://github.com/newrelic/nr1-observability-maps/pull/68
Will plan to merge later in the week then aim for a catalog update next week.

**Comment by Kav91** [comment]
Closing, feature is available.
