### ISSUE TITLE
Issue with "View Violation" button routing to invalid URL

### ISSUE THREAD

**Issue by twcallaghan** [newrelic/nr1-observability-maps#59]
I am using the most recent version of the observability maps as far as I can tell.
I am using Chrome as my browser on Windows 10.

When I click on Timeline and then "View Violation" I get this as the URL that I am being sent to for every single violation "https://60c04cc2...g0.nr-ext.net/null" (I got rid of some of it for security concerns). 

This is what I get when the website loads: 
![image](https://user-images.githubusercontent.com/23635947/109713786-a2550800-7b6f-11eb-9ec3-cfadfe2877e8.png)

I don't believe this is what should happen when you click on the "view violation" button in timeline. 
Please help and let me know if you need any further information! Thanks!

**Comment by twcallaghan** [comment]
@jpvajda I wanted to check-in to see if there has been any discussion about this bug and how to resolve it? As far as I can tell, it is just pointing to the wrong URL. Thanks!

**Comment by Kav91** [comment]
Hi @twcallaghan currently I'm not able to replicate the issue.
This one is a bit tricky to debug, so few requests. Does this happen to all alert violations shown in the timeline or just some?
I'm curious as to how you even get taken to that address, so lets validate some things.

Are you able to go to -> https://api.newrelic.com/graphiql
Then do the following graphql query and update with the entity guid for a particular service and the time frame.

```
{
  actor {
    entities(guids: "MTYwNjg2MnxBUE18QVBQTElDQVRJT058NTAxMTYzNDg") {
      ... on AlertableEntity {
        alertSeverity
        alertViolations(startTime: 1618921821449, endTime: 1619008221449) {
          violationUrl
          violationId
          openedAt
        }
      }
    }
  }
}
```

In the response do you get a violationUrl and if you browse to it manually it should do a redirect, and when the redirect is done does it successfully take you to the violation page or do you end up with the same error?

**Comment by twcallaghan** [comment]
@Kav91 I actually am unable to recreate the issue myself now, so I don't think it is an issue anymore. If I had to guess, it was a faulty link or was an issue with SSO.
I'm going to close out this issue with this comment and I will comment again here in the future if it happens again. 
Thanks!
