### ISSUE TITLE
Add core open-source template files

### ISSUE THREAD

**Issue by jbeveland27** [newrelic/nr1-observability-maps#6]
Currently missing `.releaserc.`, `.github/*`, and `.circleci`. 

Will need to review the CI/CD pipeline for potentially moving to GitHub Actions.

**Comment by Kav91** [comment]
@devfreddy is this one for you to add, or is there a doc I should follow to implement?

**Comment by jbeveland27** [comment]
Hey @Kav91 - this is mostly to have on our radar for now. The current template for OSS is here: [https://github.com/newrelic/open-source-tools/tree/master/nerdpacks/oss-template](https://github.com/newrelic/open-source-tools/tree/master/nerdpacks/oss-template). 

Circle has some setup that @devfreddy has historically done by hand, but we're looking at potentially swapping it out for GitHub Actions. We're planning on working through a backlog of issues around standardization of the Nerdpacks starting the week of 3/16.

**Comment by Kav91** [comment]
@jbeveland27 great, thanks for the info will leave it with you!
