### ISSUE TITLE
Unable to zoom in/out or move the observability maps.

### ISSUE THREAD

**Issue by sreelekhadantu** [newrelic/nr1-observability-maps#71]
**Description**
Unable to zoom in/out or move the observability maps.

![image](https://user-images.githubusercontent.com/85102841/120339783-67c05000-c2c3-11eb-99fa-2b528b035e29.png)

**Steps to Reproduce**
Previously, when we used to scroll the observability maps would zoom in/out and we could move the map. But now we do not see any such option.

**Expected Behavior**

We should be able to move the map and zoom in/out for better visibility. Now, the maps are just stuck which is a bad user experience. We could also add an on screen zoom in/out buttons to make it more feasible.

**Your Environment**

* Browser name and version:  Google Chrome Version 91.0.4472.77
* Operating System and version: Windows 10 Enterprise Version 19042.985

**Comment by Kav91** [comment]
@sreelekhadantu apologies for this issue, it was unintended during the last update.
Fix has been merged to master, when this PR -> https://github.com/newrelic/nr1-catalog/pull/264 is merged all users will then be automatically updated to the latest release.
