### ISSUE TITLE
Observability maps - Bugs 

### ISSUE THREAD

**Issue by Aparna-Mahesh** [newrelic/nr1-observability-maps#98]
Hower attributes are not fetching with names.
Not able to attached/search all Dashboards( Can scroll only up to specific alphabet).
Custom icon images are broken when using it from google.

## Relevant Logs / Console output

Attached Screenshots.

## Your Environment

NonProd

* NR1 CLI version used: NA
* Browser name and version: NA
* Operating System and version: NA

Case # 00205933

**Comment by Aparna-Mahesh** [comment]
<img width="730" alt="Dashboard errors" src="https://github.com/newrelic/nr1-observability-maps/assets/171771557/71a70cd9-5f92-41f1-9b98-d71b939aa783">
<img width="743" alt="Broken Icon" src="https://github.com/newrelic/nr1-observability-maps/assets/171771557/080acf49-f3ed-418a-ad3a-7aae3e5e453c">
<img width="820" alt="Hower Attributes" src="https://github.com/newrelic/nr1-observability-maps/assets/171771557/b36b2283-f6e4-400b-a015-6cf6b12435f5">

**Comment by Kav91** [comment]
Icon/circle issue is resolved.
